### ISSUE TITLE
ES6 class inheritance: no-unused-or-undeclared is generated for existent property or method

### ISSUE THREAD

**Issue by alopatindev** [globetro/eslint-plugin-private-props#6]
Example:
```javascript
class Foo {
    constructor() {
        this._foo = 1;
    }

    increment() {
        this._foo++;
    }
}

class Bar extends Foo {
    decrement() {
        this._foo--; // generates "'_foo' is undeclared"
    }
}
```

**Comment by globetro** [comment]
Thanks for the feedback. This is actually intended behavior, as this plugin is meant for "private" properties only, and as such any access to them outside of the class would generate an error. In the case you're outlining, that would be a "protected" property (which doesn't really exist in JavaScript). 

Also given that eslint doesn't keep context across files, I'm not sure there'd even be a way to detect this case.
