### ISSUE TITLE
Option to allow in same module

### ISSUE THREAD

**Issue by aikar** [globetro/eslint-plugin-private-props#8]
Could we have an option to allow usage of ._ if the 2 files are in the same module - so that the inspection only errors if you use a ._ method on someone elses code?

Similar to #7, would help with linking implementation details between 2 files, and make it clear to users the method is not public.

**Comment by globetro** [comment]
I would say that if you're intending to use a method in a sub-class, then you wouldn't want to prefix it with a underscore. This plugin assumes all methods starting with underscore are private (and not "protected" or "public").

**Comment by aikar** [comment]
I understand that, but I'm asking to give more flexibility in controlling non-error reach-ability.

If I have a class that has a non underscore method in a library, and the end user sees it there (IDE's are going to provide code completion, so its very easy to see), it's unclear if that method is intended to be public or not, or was it simply not documented but intended to be.

If I can name all implementation details with an underscore, that makes it very clear.

Please reconsider, as this plugin is great, but will require a lot of eslint disable comments to get around this issue.
